// Skybox: the night sky, a cube map drawn behind everything else.
// See docs/modules/renderer/skybox.md
#pragma once

#include "gfx/Cubemap.hpp"
#include "gfx/Mesh.hpp"

#include <glm/glm.hpp>

namespace gfx {
class Shader;
} // namespace gfx

namespace game {

enum class ViewMode;

/// What can be changed about the sky while the game runs. The debug UI edits the fields.
struct SkyboxSettings {
    /// Whether the sky is drawn. Without it the background is the clear colour.
    bool enabled = true;
    /// The linear colours of the sky pictures are multiplied by this number: 1 leaves
    /// them as they are, 0 is black. The pictures are dark (a night sky is a backdrop)
    /// and the tone mapping curve of the composite pass presses dark tones down further,
    /// so the default lifts them: the stars and the moon then pass 1 in the HDR buffer
    /// and stay the brightest things in the sky.
    float brightness = 2.2F;
};

/// Draws the sky: six pictures (a cube map) on the inside of a cube around the camera.
///
/// The cube does not stand anywhere in the maze. It is drawn as if the camera were
/// always in its middle, so the sky turns with the camera but never comes closer: it
/// looks infinitely far away. It is drawn LAST, at the largest possible depth, so it
/// fills exactly the pixels nothing else was drawn on.
///
/// The pictures are generated by tools/blender/make_skybox.py. The moon is painted where
/// the default moon light of game::LightingSettings comes from. The picture is fixed:
/// moving the moon light in the Lights panel does not move the painted moon.
///
/// It owns OpenGL objects, so it must be destroyed before the window.
class Skybox {
public:
    /// Loads the six pictures from assets/skybox and uploads the cube. When a picture
    /// cannot be loaded, or the six do not fit together, the error is logged and draw
    /// does nothing: the clear colour stays as the background.
    Skybox();

    /// True when the six pictures were loaded.
    bool isValid() const { return m_cubemap.isValid(); }

    /// The cube map of the sky, read only: the reflect program reads the same six
    /// pictures to show the sky on the crystals and the puddles (environment mapping).
    /// Not valid when the pictures could not be loaded.
    const gfx::Cubemap& cubemap() const { return m_cubemap; }

    /// Draws the sky with the skybox program (skybox.vert and skybox.frag). It selects
    /// the program and sets all of its uniforms itself. Call it after everything opaque
    /// in the frame has been drawn, with the depth test switched on.
    ///
    /// view and projection are the matrices of the frame, the same ones the maze is
    /// drawn with. The shader ignores the translation in view.
    ///
    /// viewMode: with ViewMode::Textured the pictures are shown. In the two debug views
    /// (normals and texture coordinates as colours) the sky shows, in the same colour
    /// coding as the normals, the direction every one of its pixels is looked up with.
    /// That direction is the texture coordinate of a cube map, so both views show data
    /// of the sky the way they show data of the walls.
    ///
    /// While it draws, the depth test passes at equal depth (GL_LEQUAL) and depth writes
    /// are off. Both are put back (GL_LESS, writes on) before the function returns.
    void draw(const gfx::Shader& shader, const glm::mat4& view, const glm::mat4& projection,
              const SkyboxSettings& settings, ViewMode viewMode) const;

private:
    gfx::Cubemap m_cubemap;
    gfx::Mesh m_cube;
};

} // namespace game
